"""Offline evidence tool.
  python tools/offline_audit.py manifest                 -> configs/runtime_files.json + docs/OFFLINE_FILES.md (every file --full reads, sha256, bytes)
  python tools/offline_audit.py trace WAV [WAV ...]      -> run --full once under an audit hook; report every DATA file Python opened / the OS mapped that is
                                                            outside the project (code/dll/pyd excluded) -> must be empty
  python tools/offline_audit.py clone DIR                -> fresh `git clone` of the repo into DIR + copy of ONLY the manifest files into DIR/Prototype/models
Native libraries (sherpa-onnx, onnxruntime, sentencepiece) open their model files in C++ where an audit hook cannot see them; that gap is closed by the
`clone` check (a run from a clone holding only the manifest files cannot read anything else)."""
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
M = "models"
FILES = [  # (path relative to Prototype, reader, required)
    (f"{M}/silero_vad.onnx", "stages/vad_silero.py via sherpa-onnx VAD", True),
    (f"{M}/asr/zipformer-vi-int8/encoder-epoch-12-avg-8.int8.onnx", "stages/asr_sherpa.py", True),
    (f"{M}/asr/zipformer-vi-int8/decoder-epoch-12-avg-8.int8.onnx", "stages/asr_sherpa.py (factory.ASR_DECODER)", True),
    (f"{M}/asr/zipformer-vi-int8/joiner-epoch-12-avg-8.int8.onnx", "stages/asr_sherpa.py", True),
    (f"{M}/asr/zipformer-vi-int8/tokens.txt", "stages/asr_sherpa.py", True),
    (f"{M}/nmt/vi-en-int8-arm64/encoder_model_quantized.onnx", "stages/nmt_ort.py (onnxruntime)", True),
    (f"{M}/nmt/vi-en-int8-arm64/decoder_model_merged_quantized.onnx", "stages/nmt_ort.py (onnxruntime)", True),
    (f"{M}/nmt/vi-en-int8-arm64/source.spm", "stages/nmt_ort.py (sentencepiece, local file)", True),
    (f"{M}/nmt/vi-en-int8-arm64/target.spm", "stages/nmt_ort.py (sentencepiece, local file)", True),
    (f"{M}/nmt/vi-en-int8-arm64/vocab.json", "stages/nmt_ort.py", True),
    (f"{M}/nmt/vi-en-int8-arm64/config.json", "stages/nmt_ort.py", True),
    (f"{M}/tts/vits-piper-en_US-ljspeech-medium/en_US-ljspeech-medium.onnx", "stages/tts_piper.py via sherpa-onnx", True),
    (f"{M}/tts/vits-piper-en_US-ljspeech-medium/tokens.txt", "stages/tts_piper.py", True),
    (f"{M}/branch_b/band_feats.onnx", "branch_b.py (built by branch_b_graph.py)", True),
    (f"{M}/branch_b/swiftf0_model.onnx", "branch_b.load_swiftf0 (byte-identical copy of the swift-f0 wheel's model.onnx)", True),
    (f"{M}/denoise/gtcrn_simple.onnx", "stages/denoise.py - ONLY when denoise_mode != off (default off, ADR-001)", False),
]
TRACKED_CONFIGS = ["configs/pipeline.json", "configs/branch_b.json", "configs/gate.json", "configs/safety_lexicon_vi_en.json"]
ESPEAK = f"{M}/tts/vits-piper-en_US-ljspeech-medium/espeak-ng-data"


def sha(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def collect() -> list:
    rows = [{"path": p, "reader": r, "required": q} for p, r, q in FILES]
    for f in sorted((ROOT / ESPEAK).rglob("*")):
        if f.is_file():
            rows.append({"path": f.relative_to(ROOT).as_posix(), "reader": "espeak-ng phonemizer data_dir (tts_piper.py)", "required": True})
    for r in rows:
        r["bytes"] = (ROOT / r["path"]).stat().st_size
        r["sha256"] = sha(ROOT / r["path"])
    return rows


def cmd_manifest() -> None:
    rows = collect()
    (ROOT / "configs/runtime_files.json").write_text(json.dumps(rows, indent=1), encoding="utf8")
    by = {}
    n_espeak = 0
    for r in rows:
        is_e = "espeak-ng-data" in r["path"]
        n_espeak += is_e
        key = (ESPEAK + "/ (all files)") if is_e else r["path"]
        d = by.setdefault(key, {"bytes": 0, "reader": r["reader"], "required": r["required"]})
        d["bytes"] += r["bytes"]
    req = sum(d["bytes"] for d in by.values() if d["required"])
    out = ["# Files read by `python -m tonebridge.cli --full` (offline inventory)", "",
           "Generated by `tools/offline_audit.py manifest`; sha256 in `configs/runtime_files.json`. Paths are relative to `Prototype/`. Nothing is read from a "
           "library cache (HF hub, torch hub, XDG cache): `tests/test_offline.py` redirects those caches to empty dirs and requires them to stay empty, "
           "and the clean-clone run (`reports/LAPTOP_RESULTS.md` section 0) holds only the files below.", "",
           "| file | bytes | read by | required |", "|---|---|---|---|"]
    out += [f"| `{k}` | {d['bytes']:,} | {d['reader']} | {'yes' if d['required'] else 'optional'} |" for k, d in by.items()]
    out += ["", f"espeak-ng-data: {n_espeak} files. Required model/voice data total: {req:,} bytes ({req / 2**20:.1f} MiB).", "",
            "Tracked configs read at run time: " + ", ".join(f"`{c}`" for c in TRACKED_CONFIGS) + ".", "",
            "Python code dependencies (code, not data; installed in `.venv`): onnxruntime, sherpa-onnx, sentencepiece, numpy, scipy, psutil, pydantic, "
            "swift-f0 (its bundled `model.onnx` is NOT opened: `branch_b.load_swiftf0` builds the session from `models/branch_b/swiftf0_model.onnx`)."]
    (ROOT / "docs/OFFLINE_FILES.md").write_text("\n".join(out) + "\n", encoding="utf8")
    print("\n".join(out))


def cmd_trace(wavs: list) -> None:
    import psutil
    opened = set()
    sys.addaudithook(lambda ev, a: opened.add(str(a[0])) if ev == "open" and isinstance(a[0], (str, Path)) else None)
    sys.path.insert(0, str(ROOT / "src"))
    import numpy as np
    from scipy.io import wavfile
    from tonebridge.config import PipelineConfig
    from tonebridge.pipeline import Pipeline
    from tonebridge.stages.factory import real_full
    cfg = PipelineConfig.load(ROOT / "configs/pipeline.json")
    pipe = Pipeline(cfg, real_full(cfg))
    for w in wavs:
        sr, x = wavfile.read(w)
        pipe.run(x.astype(np.float32) / 32768.0, utt_id=Path(w).stem)
    mapped = {m.path for m in psutil.Process().memory_maps()}
    code_ext = (".py", ".pyc", ".pyd", ".dll", ".so", ".exe", ".manifest", ".cfg", ".pth", ".pyi")
    root = str(ROOT).lower()
    allp = opened | mapped
    outside = sorted(p for p in allp if os.path.isabs(p) and not p.lower().startswith(root) and not p.lower().endswith(code_ext)
                     and os.path.isfile(p) and "windows" not in p.lower() and "__pycache__" not in p)
    inside = sorted(os.path.relpath(p, ROOT) for p in allp if p.lower().startswith(root) and os.path.isfile(p) and "__pycache__" not in p
                    and not p.lower().endswith(code_ext))
    print("PROJECT data files seen by Python/OS mmap:", *inside, sep="\n  ")
    print("DATA files outside the project (excluding code/dll/pyd):", *(outside or ["  (none)"]), sep="\n  ")
    sys.exit(1 if outside else 0)


def cmd_clone(dst: str) -> None:
    dst_p = Path(dst)
    assert not dst_p.exists(), f"{dst} exists; use a new directory"
    subprocess.run(["git", "clone", "--quiet", str(ROOT.parent), str(dst_p)], check=True)
    rows = json.loads((ROOT / "configs/runtime_files.json").read_text())
    n = 0
    for r in rows:
        if not r["required"]:
            continue
        d = dst_p / "Prototype" / r["path"]
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / r["path"], d)
        assert sha(d) == r["sha256"], r["path"]
        n += 1
    print(f"clone ready: {dst_p / 'Prototype'} ({n} model files copied, hashes verified)")


if __name__ == "__main__":
    {"manifest": cmd_manifest, "trace": lambda: cmd_trace(sys.argv[2:]), "clone": lambda: cmd_clone(sys.argv[2])}[sys.argv[1]]()
